/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas1;

/**
 *
 * @author Prdigma
 */
public class from1 extends javax.swing.JFrame {

    /**
     * Creates new form from1
     */
    public from1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Harga1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Harga2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Harga3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Diskon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Form Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 90, 14);

        jLabel2.setText("Harga Barang 1 :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 90, 14);
        getContentPane().add(Harga1);
        Harga1.setBounds(130, 40, 120, 20);

        jLabel3.setText("Harga Barang 2 :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 90, 14);
        getContentPane().add(Harga2);
        Harga2.setBounds(130, 70, 120, 20);

        jLabel4.setText("Harga Barang 3 :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 90, 14);
        getContentPane().add(Harga3);
        Harga3.setBounds(130, 100, 120, 20);

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 150, 31, 14);

        Diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiskonActionPerformed(evt);
            }
        });
        getContentPane().add(Diskon);
        Diskon.setBounds(110, 150, 70, 20);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 190, 65, 23);

        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 240, 22, 14);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 230, 166, 96);

        jLabel7.setText("%");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 150, 34, 14);

        setBounds(0, 0, 416, 404);
    }// </editor-fold>//GEN-END:initComponents

    private void DiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiskonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int hrg1 = Integer.parseInt(Harga1.getText());
            int hrg2 = Integer.parseInt(Harga2.getText());
            int hrg3 = Integer.parseInt(Harga3.getText());
            int diskon = Integer.parseInt(Diskon.getText());
            
            int harga = hrg1+hrg2+hrg3;
            int hasil = harga*diskon/100;
            int total = harga-hasil;
            
            Hasil.append("Harga Barang 1 : " + hrg1+"\n");
            Hasil.append("Harga Barang 2 : " + hrg2+"\n");
            Hasil.append("Harga Barang 3 : " + hrg3+"\n");
            Hasil.append("Harga total sebelum diskon : " + harga+"\n");

            Hasil.append("Diskon : " + hasil+"\n");
            Hasil.append("Total pembayaran : " + total+"\n");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JTextField Harga1;
    private javax.swing.JTextField Harga2;
    private javax.swing.JTextField Harga3;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
